language: node_js

node_js: 
  - 8
  - 10
  - 12
  - node

before_install: # Install Cassandra
  - wget http://archive.apache.org/dist/cassandra/4.0-alpha2/apache-cassandra-4.0-alpha2-bin.tar.gz
  - tar -xzf apache-cassandra-4.0-alpha2-bin.tar.gz
  - export PATH="$PWD/apache-cassandra-4.0-alpha2/bin/:$PATH"
  - cassandra
  - sleep 20

script:
  - npm run setup:db
  - npm run build
  - npm test
